"""Track A — pluggable *model-pane* provider.

Design note (why this file is small):
    The UID and Weight panes are NEVER generated by a model. A hallucinated
    UID string or an invented scale reading would fail — and legally
    misrepresent — government portal compliance, and generative models are
    unreliable at rendering exact alphanumerics/digits anyway. Those panes are
    produced deterministically by ``compositor.py``.

    The only pane where generation adds value is the clean *model/product*
    shot. This module abstracts that single step behind a provider interface
    so the free build ships today and a sub-1-rupee generative model can be
    switched on later purely via configuration.

Providers and their per-image cost:
    passthrough  0 INR  — uploaded image, lightly enhanced (no dependency)
    rembg        0 INR  — local background removal (optional dependency)
    flux       ~0.25 INR — hosted FLUX.1 [schnell] (needs FAL_KEY/REPLICATE token)
"""
from __future__ import annotations

from dataclasses import dataclass

from PIL import Image, ImageOps

from ..config import settings


class ProviderNotConfigured(RuntimeError):
    """Raised when a provider cannot run (e.g. missing key/dependency)."""


class CostCeilingExceeded(RuntimeError):
    """Raised when a provider's per-image cost breaches ``max_cost_inr``."""


@dataclass
class ModelPaneResult:
    image: Image.Image
    provider: str
    cost_inr: float
    billable_to_client: bool


class ModelPaneProvider:
    """Base class. ``cost_inr`` is the per-image cost this provider incurs."""

    name = "base"
    cost_inr = 0.0

    def enhance(self, model_img: Image.Image) -> Image.Image:  # pragma: no cover
        raise NotImplementedError

    def run(self, model_img: Image.Image) -> ModelPaneResult:
        if self.cost_inr > settings.max_cost_inr:
            raise CostCeilingExceeded(
                f"{self.name} costs {self.cost_inr} INR/image, over the "
                f"{settings.max_cost_inr} INR ceiling."
            )
        out = self.enhance(model_img)
        return ModelPaneResult(
            image=out,
            provider=self.name,
            cost_inr=self.cost_inr,
            billable_to_client=self.cost_inr > 0 and settings.bill_api_cost_to_client,
        )


class PassthroughProvider(ModelPaneProvider):
    """Free, zero-dependency default: normalise + gently enhance the photo."""

    name = "passthrough"
    cost_inr = 0.0

    def enhance(self, model_img: Image.Image) -> Image.Image:
        # Autocontrast makes studio-on-white shots pop without inventing pixels.
        return ImageOps.autocontrast(model_img, cutoff=1)


class RembgProvider(ModelPaneProvider):
    """Free, local background removal (studio-clean look) via `rembg`."""

    name = "rembg"
    cost_inr = 0.0

    def enhance(self, model_img: Image.Image) -> Image.Image:
        try:
            from rembg import remove  # type: ignore
        except ImportError as exc:  # pragma: no cover - optional dep
            raise ProviderNotConfigured(
                "rembg not installed. `pip install rembg onnxruntime` or use "
                "HALLMARK_AI_PROVIDER=passthrough."
            ) from exc
        cut = remove(model_img)  # RGBA with alpha
        white = Image.new("RGB", cut.size, (255, 255, 255))
        white.paste(cut, mask=cut.split()[-1])
        return white


class FluxProvider(ModelPaneProvider):
    """Hosted FLUX.1 [schnell] generation (~0.25 INR/image).

    Intentionally a thin, guarded stub: it validates configuration and cost,
    but the actual network call is left as a single clearly-marked spot so the
    free prototype never makes a paid request by accident.
    """

    name = "flux"
    cost_inr = 0.25  # ~ $0.003 at ~83 INR/USD; well under the 1 INR ceiling

    def enhance(self, model_img: Image.Image) -> Image.Image:  # pragma: no cover
        if not (settings.fal_api_key or settings.replicate_api_token):
            raise ProviderNotConfigured(
                "FLUX provider needs FAL_KEY or REPLICATE_API_TOKEN. Falling "
                "back to the free provider keeps you at 0 INR/image."
            )
        # --- Paid network call would go here ---
        # Submit `model_img` + a studio-shot prompt to FLUX.1 [schnell] on
        # fal.ai / Replicate and return the rendered product image. Kept
        # unimplemented on purpose so the prototype is cost-free by default.
        raise ProviderNotConfigured(
            "FLUX network call is not wired in this prototype build."
        )


_PROVIDERS: dict[str, type[ModelPaneProvider]] = {
    PassthroughProvider.name: PassthroughProvider,
    RembgProvider.name: RembgProvider,
    FluxProvider.name: FluxProvider,
}


def get_model_pane(model_img: Image.Image,
                   provider: str | None = None) -> ModelPaneResult:
    """Run the configured provider, falling back to free passthrough on any
    configuration/cost problem so a request never fails just because the paid
    tier is unavailable."""
    name = (provider or settings.ai_provider or "passthrough").lower()
    provider_cls = _PROVIDERS.get(name, PassthroughProvider)
    try:
        return provider_cls().run(model_img)
    except (ProviderNotConfigured, CostCeilingExceeded):
        if provider_cls is PassthroughProvider:
            raise
        return PassthroughProvider().run(model_img)
